services:
  # ollama:
  #   image: ollama/ollama
  #   container_name: ollama2
  #   volumes:
  #     - ollama:/root/.ollama
  #   ports:
  #     - "11435:11434" # Внутренний порт для Ollama, будет использоваться NGINX
  #   restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certifies:/etc/ssl:ro
      # - ./nginx/templates/default.conf.template:/etc/nginx/templates/nginx.conf.template:ro   # Раскоментить, если хотим юзать прееменные окружения для nginx
    ports:
      - "443:443" # HTTPS порт
      - "80:80"   # HTTP порт (для редиректа на HTTPS)

    # Раскоментить, если хотим юзать прееменные окружения для nginx    
    # environment:
      # FRONTEND_HOST: ${FRONTEND_HOST}
      # FRONTEND_PORT: ${FRONTEND_PORT}



    # depends_on:
    #   - ollama



    # Раскоментить, если хотим юзать прееменные окружения для nginx
    # command: /bin/sh -c "envsubst < /etc/nginx/templates/nginx.conf.template > /etc/nginx/nginx.conf && exec nginx -g 'daemon off;'"

    restart: unless-stopped


  postgres:
    image: postgres:latest
    container_name: postgres-db
    ports:
      - "${DB_PORT}:5432"  # Порт берется из .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
volumes:
  ollama:
    driver: local

  nginx:
    driver: local